export const WELCOME = [
  "◈ *BYTECLAW SYSTEM ONLINE* ◈",
  "",
  "🤖 AI codebase assistant connected successfully.",
  "",
  "Choose a command to begin:",
  "",
  "╭────────────────────╮",
  "│ 🔎 `/ask`",
  "│ Ask questions about your code",
  "│",
  "│ 🧠 `/agent`",
  "│ Execute codebase changes with approval",
  "│",
  "│ 🧭 `/plan`",
  "│ Generate a step-by-step build plan",
  "╰────────────────────╯",
  "",
  "⚙️ _Example:_ `/plan build authentication flow`",
  "",
  "Awaiting your command.",
].join("\n");